name: 'integration test'

on:
  pull_request:
    branches:
      - main

jobs:
  integration-test:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:latest
      volumes:
        - .:/src
    env:
      MYSQLD_MAJOR_VERSION: "8.4"
    steps:
      - name: Check-out
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Build
        run: pwd; ls; bash -x ci/build.sh
      - name: Run integration test
        run: pwd; ls; bash -x ci/run_integration_tests.sh
